import img3 from "../img/img3.jpg";
import img5 from "../img/img5.jpg";
import img6 from "../img/img6.jpg";
import img7 from "../img/img7.jpg";
import img8 from "../img/img8.jpg";
const Producta = [
  {
    id: 1,
    name: "Corneto Pizza",
    moniy: "$28",
    image:
      img3,
    catigoriy: "Pizza",
  },
  {
    id: 2,
    name: "Beeferist Burger",
    moniy: "$22",
    image:img6,
    catigoriy: "Burger",
  },
  {
    id: 3,
    name: "Sausage Pizza",
    moniy: "$26",
    image: img3,
    catigoriy: "Pizza",
  },
  {
    id: 4,
    name: "Dorayaki Burger",
    moniy: "$24",
    image:img7,
    catigoriy: "Burger",
  },
  {
    id: 5,
    name: "   Brey Sandwich",
    moniy: "$26",
    image: img5,
    catigoriy: "Sandwich",
  },
  {
    id: 6,
    name: "Tomato Pizza",
    moniy: "$22",
    image: img6,
    catigoriy: "Pizza",
  },
  {
    id: 7,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
  {
    id: 8,
    name: "Cheese Pizza",
    moniy: "$26",
    image: img8,
    catigoriy: "Pizza",
  },
  {
    id: 9,
    name: "Tomato Pizza",
    moniy: "$22",
    image: img6,
    catigoriy: "Pizza",
  },
  {
    id: 10,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
  {
    id: 11,
    name: "Cheese Pizza",
    moniy: "$26",
    image: img8,
    catigoriy: "Pizza",
  },
  {
    id: 12,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
  {
    id: 13,
    name: "   Brey Sandwich",
    moniy: "$26",
    image: img5,
    catigoriy: "Sandwich",
  },
  {
    id: 14,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
  {
    id: 15,
    name: "Corneto Pizza",
    moniy: "$28",
    image:img5,
    catigoriy: "Pizza",
  },
  {
    id: 16,
    name: "Beeferist Burger",
    moniy: "$22",
    image:img5,
    catigoriy: "Burger",
  },
  {
    id: 17,
    name: "Sausage Pizza",
    moniy: "$26",
    image: img3,
    catigoriy: "Pizza",
  },
  {
    id: 18,
    name: "Dorayaki Burger",
    moniy: "$24",
    image:img3,
    catigoriy: "Burger",
  },
  {
    id: 19,
    name: "   Brey Sandwich",
    moniy: "$26",
    image: img5,
    catigoriy: "Sandwich",
  },
  {
    id: 20,
    name: "Tomato Pizza",
    moniy: "$22",
    image: img6,
    catigoriy: "Pizza",
  },
  {
    id: 21,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
  {
    id: 22,
    name: "Cheese Pizza",
    moniy: "$26",
    image: img8,
    catigoriy: "Pizza",
  },
  {
    id: 23,
    name: "Tomato Pizza",
    moniy: "$22",
    image: img6,
    catigoriy: "Pizza",
  },
  {
    id: 24,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
  {
    id: 25,
    name: "Cheese Pizza",
    moniy: "$26",
    image: img8,
    catigoriy: "Pizza",
  },
  {
    id: 26,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
  {
    id: 27,
    name: "   Brey Sandwich",
    moniy: "$26",
    image: img5,
    catigoriy: "Sandwich",
  },
  {
    id: 28,
    name: "Shiren Hot Dog",
    moniy: "$24",
    image: img7,
    catigoriy: "HodDog",
  },
];
export default Producta;
